version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      gradle-minor-patch:
        update-types: [ "minor", "patch" ]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "gradle"
